
services:
  db:
    image: mysql:latest
    container_name: dockmates_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dockmates_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - dockmates_data:/var/lib/mysql
      - ./Database/dockmates_backup.sql:/docker-entrypoint-initdb.d/dockmates_backup.sql

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: my_backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/dockmates_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  frontend:
    build:
      context: ./Frontend/DockMates
      dockerfile: Dockerfile
    container_name: my_frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  dockmates_data:

